/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolp3unidade;

import Classes.Controle;
import Classes.Funcionario;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Thamires
 */
public class PainelCadastro extends javax.swing.JFrame {

    /**
     * Creates new form PainelCadastro
     */
         //Objeto para execultar as funçoes de sair e salvar
    //Objeto para execultar as funçoes de sair e salvar
    Controle C = new Controle();
    
    //Construtor que recebe um Controle
    public PainelCadastro(Controle c) {
        initComponents();
        setLocationRelativeTo(null);
        this.C = c; //Associa o Controle recebido ao atributo da classe
    }
    
    public PainelCadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastro = new javax.swing.JPanel();
        botãoExibir = new javax.swing.JButton();
        campvalorh = new javax.swing.JTextField();
        campofuncionario = new javax.swing.JLabel();
        camphorastra = new javax.swing.JTextField();
        lblnome = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lbldata = new javax.swing.JLabel();
        lblvalorh = new javax.swing.JLabel();
        lblhorastra = new javax.swing.JLabel();
        campnome = new javax.swing.JTextField();
        campdata = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        imagementrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botãoExibir.setBackground(new java.awt.Color(204, 204, 255));
        botãoExibir.setForeground(new java.awt.Color(102, 102, 255));
        botãoExibir.setText("Exibir");
        botãoExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoExibirActionPerformed(evt);
            }
        });
        PainelCadastro.add(botãoExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        campvalorh.setBackground(new java.awt.Color(153, 153, 255));
        campvalorh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campvalorhActionPerformed(evt);
            }
        });
        PainelCadastro.add(campvalorh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 71, 30));

        campofuncionario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campofuncionario.setForeground(new java.awt.Color(153, 153, 255));
        campofuncionario.setText("Cadastro de Funcionários");
        PainelCadastro.add(campofuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        camphorastra.setBackground(new java.awt.Color(153, 153, 255));
        PainelCadastro.add(camphorastra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 71, 30));

        lblnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnome.setForeground(new java.awt.Color(153, 153, 255));
        lblnome.setText("Nome:");
        PainelCadastro.add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 107, -1, -1));

        btnSair.setBackground(new java.awt.Color(204, 204, 255));
        btnSair.setForeground(new java.awt.Color(102, 102, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        PainelCadastro.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 300, 60, -1));

        lbldata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldata.setForeground(new java.awt.Color(153, 153, 255));
        lbldata.setText("Data de Admissão:");
        PainelCadastro.add(lbldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 151, -1, -1));

        lblvalorh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblvalorh.setForeground(new java.awt.Color(153, 153, 255));
        lblvalorh.setText("Valor Hora:");
        PainelCadastro.add(lblvalorh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lblhorastra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblhorastra.setForeground(new java.awt.Color(153, 153, 255));
        lblhorastra.setText("Horas Trabalhadas:");
        PainelCadastro.add(lblhorastra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        campnome.setBackground(new java.awt.Color(153, 153, 255));
        campnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campnomeActionPerformed(evt);
            }
        });
        PainelCadastro.add(campnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 102, 410, 30));

        campdata.setBackground(new java.awt.Color(153, 153, 255));
        try {
            campdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campdataActionPerformed(evt);
            }
        });
        PainelCadastro.add(campdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 147, 70, 30));

        btnSalvar.setBackground(new java.awt.Color(204, 204, 255));
        btnSalvar.setForeground(new java.awt.Color(102, 102, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        PainelCadastro.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        imagementrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolp3unidade/Imagem entrada/Rosa e Roxo.jpeg"))); // NOI18N
        PainelCadastro.add(imagementrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoExibirActionPerformed
        new PainelExibição(C).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoExibirActionPerformed

    private void campvalorhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campvalorhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campvalorhActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
     // Verifica se todos os campos estão vazios
    if (campnome.getText().trim().isEmpty() &&
        campdata.getText().trim().isEmpty() &&
        campvalorh.getText().trim().isEmpty() &&
        camphorastra.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos os campos precisam ser preenchidos!", "Aviso", JOptionPane.WARNING_MESSAGE);
        return; // Interrompe a execução do método
    }

    // Verifica se algum campo específico está vazio
    if (campnome.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo 'Nome' precisa ser preenchido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        campnome.requestFocus();
        return;
    }
    if (campdata.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo 'Data de Admissão' precisa ser preenchido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        campdata.requestFocus();
        return;
    }
    if (campvalorh.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo 'Valor Hora' precisa ser preenchido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        campvalorh.requestFocus();
        return;
    }
    if (camphorastra.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo 'Horas Trabalhadas' precisa ser preenchido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        camphorastra.requestFocus();
        return;
    }
        try {
          //Captura e valida os campos de entrada
            String nome = campnome.getText();
            String dataAdmissao = campdata.getText();
            float valorHora = Float.parseFloat(campvalorh.getText());
            float horasTrabalhadas = Float.parseFloat(camphorastra.getText());

            //Cria o funcionário com os dados capturados
            Funcionario funcionario = new Funcionario(nome, dataAdmissao, valorHora, horasTrabalhadas);

            //Salva o funcionário e exibe mensagens
            if (C.salvar(funcionario)) {
                JOptionPane.showMessageDialog(this, "Funcionário Cadastrado com Sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                //Limpa os campos e coloca foco no nome
                campnome.setText("");
                campdata.setText("");
                campvalorh.setText("");
                camphorastra.setText("");
                campnome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Funcionário!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Os Campos 'Valor Hora' e 'Horas Trabalhadas' devem ser Numéricos!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data de Admissão Inválida. Use o Formato DD/MM/AAAA!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {// Captura e trata exceções relacionadas a dados inválidos (como nome vazio ou valores negativos)
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void campnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campnomeActionPerformed

    private void campdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadastro;
    private javax.swing.JButton botãoExibir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField campdata;
    private javax.swing.JTextField camphorastra;
    private javax.swing.JTextField campnome;
    private javax.swing.JLabel campofuncionario;
    private javax.swing.JTextField campvalorh;
    private javax.swing.JLabel imagementrada;
    private javax.swing.JLabel lbldata;
    private javax.swing.JLabel lblhorastra;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblvalorh;
    // End of variables declaration//GEN-END:variables
}
